name: publish-winget

on:
  release:
    types: [published]

jobs:
  package_exists:
    runs-on: ubuntu-latest
    outputs: 
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - id: check
        run: |
          VERSION=${GITHUB_REF:11} 
          echo Looking for https://github.com/microsoft/winget-pkgs/blob/master/manifests/OpenJS/NodeJS/$VERSION.yaml
          if curl --output /dev/null --head --fail https://github.com/microsoft/winget-pkgs/blob/master/manifests/OpenJS/NodeJS/$VERSION.yaml; then
            echo "YAML exits, skipping generation"
            echo "::set-output name=exists::exists"
          else
            echo "YAML does not exists, will generate"
            echo "::set-output name=exists::not-exists"
          fi
  publish-winget:
    runs-on: ubuntu-latest
    needs: package_exists
    if: eeds.package_exists.outputs.exists == 'not-exists'
    steps:
      - name: Greet
        run: echo ${{needs.package_exists.outputs.exists}}

