name: publish-winget

on:
  release:
    types: [published]

jobs:
  publish-winget:
    runs-on: ubuntu-latest
    steps:
      - name: Test if the package isn't already published
        run: |
          VERSION=${GITHUB_REF:11}
          echo Looking for https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/OpenJS/NodeJS/$VERSION.yaml
          if curl --output /dev/null --silent --head --fail https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/OpenJS/NodeJS/$VERSION.yaml; then
            echo "Package already exists, exiting"
            exit 1
          fi
